__1.__ Найти собственные векторы и собственные значения для линейного оператора, заданного матрицей

$$A=\begin{pmatrix}
-1 & -6\\ 
2 & 6
\end{pmatrix}.$$

__Решение:__

Найдем собственные значения линейного оператора, составив и решив характеристическое уравнение:

$$\begin{vmatrix}
-1-\lambda & -6\\ 
2 & 6-\lambda
\end{vmatrix} = 0,$$

$$(-1-\lambda)\cdot(6-\lambda)-2\cdot(-6)=0$$
$$\lambda_1=2$$
$$\lambda_2=3$$

Теперь найдем собственные векторы вида $\begin{pmatrix}
x_{1}\\ 
x_{2}
\end{pmatrix}$, подставив полученное собственное значение в выражение $\textbf{A}x=\lambda x$:

$$\begin{pmatrix}
-1 & -6\\ 
2 & 6
\end{pmatrix}
\begin{pmatrix}
x_{1}\\ 
x_{2}
\end{pmatrix}=
\lambda
\begin{pmatrix}
x_{1}\\ 
x_{2}
\end{pmatrix}.
$$

Получим при $\lambda=2$

$$\begin{cases}
-x_{1}-6\cdot x_{2}= 2\cdot x_{1}, \\
2\cdot x_{1}+6\cdot x_{2}= 2\cdot x_{2}.
\end{cases}$$ 

$$x_1=-2\cdot x_2$$

$$x_2 \in \mathbb{R}$$

Получим при $\lambda=3$

$$\begin{cases}
-x_{1}-6\cdot x_{2}= 3\cdot x_{1}, \\
2\cdot x_{1}+6\cdot x_{2}= 3\cdot x_{2}.
\end{cases}$$ 

$$x_1=-\frac{3}{2}\cdot x_2$$

$$x_2 \in \mathbb{R}$$

In [11]:
import numpy as np

In [15]:
# проверка
a=np.array([[-1,-6],[2,6]])
w, v = np.linalg.eig(a)
print(f'Собственные числа: {w}')
print(f'Собственные вектора: \n{v}')

Собственные числа: [2. 3.]
Собственные вектора: 
[[-0.89442719  0.83205029]
 [ 0.4472136  -0.5547002 ]]


__2.__ Дан оператор поворота на 180 градусов, задаваемый матрицей 

$$A=\begin{pmatrix}
-1 & 0\\ 
0 & -1
\end{pmatrix}.$$

Показать, что __любой__ вектор является для него собственным.

__Решение:__


Найдем собственные значения линейного оператора, составив и решив характеристическое уравнение:

$$\begin{vmatrix}
-1-\lambda & 0\\ 
0 & -1-\lambda
\end{vmatrix} = 0,$$

$$(-1-\lambda)\cdot(-1-\lambda)-0=0$$
$$\lambda=-1$$

Теперь найдем собственные векторы вида $\begin{pmatrix}
x_{1}\\ 
x_{2}
\end{pmatrix}$, подставив полученное собственное значение в выражение $\textbf{A}x=\lambda x$:

$$\begin{pmatrix}
-1 & 0\\ 
0 & -1
\end{pmatrix}
\begin{pmatrix}
x_{1}\\ 
x_{2}
\end{pmatrix}=
\lambda
\begin{pmatrix}
x_{1}\\ 
x_{2}
\end{pmatrix}.
$$

Получим при $\lambda=-1$

$$\begin{cases}
-x_1-0\cdot x_2= -1\cdot x_{1}, \\
0\cdot x_{1}-x_{2}= -1\cdot x_{2}.
\end{cases}$$ 

$$\begin{cases}
-x_1= -x_{1}, \\
-x_2= -x_{2}.
\end{cases}$$ 

Т.е. любой вектор яв-ся собсвенным. Что и требовалось доказать

In [14]:
# проверка
a=np.array([[-1,0],[0,-1]])
w, v = np.linalg.eig(a)
print(f'Собственные числа: {w}')
print(f'Собственные вектора: \n{v}')

Собственные числа: [-1. -1.]
Собственные вектора: 
[[1. 0.]
 [0. 1.]]


__3.__ Пусть линейный оператор задан матрицей

$$A=\begin{pmatrix}
1 & 1\\ 
-1 & 3
\end{pmatrix}.$$

Установить, является ли вектор $x=(1,1)$ собственным вектором этого линейного оператора.

__Решение__

Предположим, что вектор $x$ является собственным вектором заданного линейного оператора, тогда должно существовать некоторое вещественное число $\lambda$, при котором 

$$\begin{pmatrix}
1 & 1\\ 
-1 & 3
\end{pmatrix}
\begin{pmatrix}
1\\ 
1 
\end{pmatrix}=
\lambda
\begin{pmatrix}
1\\ 
1
\end{pmatrix}.
$$

Из этого будет следовать, что 

$$\begin{cases}
1+1=1\cdot\lambda \\ 
-1+3 = 1\cdot \lambda
\end{cases}
\Rightarrow
\begin{cases}
\lambda=2\\ 
\lambda=2
\end{cases}.$$

Таким образом, вектор $x=(1,1)$ является собственным вектором линейного оператора, заданного матрицей $A$, и его собственное значение составляет $\lambda=2$

__4.__ Пусть линейный оператор задан матрицей

$$A=\begin{pmatrix}
0 & 3 & 0\\ 
3 & 0 & 0\\
0 & 0 & 3
\end{pmatrix}.$$

Установить, является ли вектор $x=(3, -3, -4)$ собственным вектором этого линейного оператора.

__Решение__

Предположим, что вектор $x$ является собственным вектором заданного линейного оператора. Аналогично методике из предыдущего примера получим:

$$\begin{pmatrix}
0 & 3 & 0\\ 
3 & 0 & 0\\
0 & 0 & 3
\end{pmatrix}
\begin{pmatrix}
3\\
-3\\
-4
\end{pmatrix}=
\lambda
\begin{pmatrix}
3\\
-3\\
-4
\end{pmatrix}
$$

$$\Rightarrow
\begin{cases}
\lambda=-\frac{1}{3}\\ 
\lambda=-\frac{1}{3}\\
\lambda=\frac{1}{3}
\end{cases}$$

Такая система не имеет смысла, следовательно, вектор $x=(3, -3, -4)$ не является собственным вектором линейного оператора, заданного матрицей $A$.

In [16]:
a = np.array([[0,3,0],[3,0,0],[0,0,3]])
b = np.array([[3],[-3],[-4]])

print(f'Матрица A\n{a}\n')
print(f'Матрица B\n{b}\n')
print(f'Матрица AB\n{np.dot(a, b)}')

Матрица A
[[0 3 0]
 [3 0 0]
 [0 0 3]]

Матрица B
[[ 3]
 [-3]
 [-4]]

Матрица AB
[[ -9]
 [  9]
 [-12]]
