__1.__ Решить систему уравнений методом Крамера:

   а) $\begin{cases}
x_{1}-2x_{2}=1 \\
3x_{1}-4x_{2}=7
\end{cases}$
    
   б) $\begin{cases}
2x_{1}-x_{2}+5x_{3}=10 \\
x_{1}+x_{2}-3x_{3}=-2 \\
2x_{1}+4x_{2}+x_{3}=1
\end{cases}$

__Решение:__

   а) $\begin{cases}
x_{1}-2x_{2}=1 \\
3x_{1}-4x_{2}=7
\end{cases}$

In [1]:
import numpy as np

In [2]:
#Найдем определитель матрицы коэффициентов:
x = [1, -2]
y = [3, -4]
a = np.array([x, y])
round(np.linalg.det(a),2)

2.0

In [3]:
## Найдем определитель А1 и А2
x = [1, -2]
y = [7, -4]
a1 = np.array([x, y])
x = [1, 1]
y = [3, 7]
a2 = np.array([x, y])
print(f'определитель А1 = {round(np.linalg.det(a1),2)}')
print(f'определитель А2 = {round(np.linalg.det(a2),2)}')

определитель А1 = 10.0
определитель А2 = 4.0


Найдем решение по формулам Крамера:

$$x_{1} = \frac{detA_{1}}{detA} = \frac{10}{2}=5$$


$$x_{2} = \frac{detA_{2}}{detA} = \frac{4}{2}=2$$


   б) $\begin{cases}
2x_{1}-x_{2}+5x_{3}=10 \\
x_{1}+x_{2}-3x_{3}=-2 \\
2x_{1}+4x_{2}+x_{3}=1
\end{cases}$

In [4]:
#Найдем определитель матрицы коэффициентов:
x = [2, -1, 5]
y = [1, 1, -3]
z = [2, 4, 1]
a = np.array([x, y, z])
round(np.linalg.det(a),2)

43.0

In [5]:
## Найдем определитель А1, А2, A3
x = [10, -1, 5]
y = [-2, 1, -3]
z = [1, 4, 1]
a1 = np.array([x, y, z])
x = [2, 10, 5]
y = [1, -2, -3]
z = [2, 1, 1]
a2 = np.array([x, y, z])
x = [2, -1, 10]
y = [1, 1, -2]
z = [2, 4, 1]
a3 = np.array([x, y, z])
print(f'определитель А1 = {round(np.linalg.det(a1),2)}')
print(f'определитель А2 = {round(np.linalg.det(a2),2)}')
print(f'определитель А3 = {round(np.linalg.det(a3),2)}')

определитель А1 = 86.0
определитель А2 = -43.0
определитель А3 = 43.0


Найдем решение по формулам Крамера:

$$x_{1} = \frac{detA_{1}}{detA} = \frac{86}{43}=2$$


$$x_{2} = \frac{detA_{2}}{detA} = \frac{-43}{43}=-1$$


$$x_{3} = \frac{detA_{3}}{detA} = \frac{43}{43}=1$$



__2*.__ Найти $L$-матрицу $LU$-разложения для матрицы коэффициентов:

   а)$$\begin{pmatrix}
1 & 2 & 4 \\ 
2 & 9 & 12 \\ 
3 & 26 & 30
\end{pmatrix}$$
    
   б)$$\begin{pmatrix}
1 & 1 & 2 & 4\\ 
2 & 5 & 8 & 9\\ 
3 & 18 & 29 & 18\\
4 & 22 & 53 & 33
\end{pmatrix}$$

__Решение__

а)

Начнем прямой ход метода Гаусса. Для этого домножим первую строку на $2$ и вычтем ее из второго уравнения. При этом запишем в матрицу $L$ на место элемента $l_{21}$ значение $2$. 

$$\begin{pmatrix}
1 & 2 & 4 \\ 
0 & 5 & 4 \\ 
3 & 26 & 30
\end{pmatrix}$$

Затем нам нужно вычесть из третьего уравнения первое, домноженное на $3$. Значит, в матрицу $L$ запишем $l_{31}=3$. 

$$\begin{pmatrix}
1 & 2 & 4 \\ 
0 & 5 & 4 \\ 
0 & 20 & 18
\end{pmatrix}$$

Далее умножим вторую строку на $4$ и вычтем ее из третьей. При этом в матрицу $L$ на место $l_{32}$ запишем $4$.

$$\begin{pmatrix}
1 & 2 & 4 \\ 
0 & 5 & 4 \\ 
0 & 0 & 2
\end{pmatrix}$$

В итоге получим

$$U=\begin{pmatrix}
1 & 2 & 4 \\ 
0 & 5 & 4 \\ 
0 & 0 & 2
\end{pmatrix}$$


$$L=\begin{pmatrix}
1 & 0 & 0 \\ 
2 & 1 & 0 \\ 
3 & 4 & 1
\end{pmatrix}$$



In [6]:
# проверка
u=np.array([[1, 2, 4], [0, 5, 4], [0, 0, 2]])
l=np.array([[1, 0, 0], [2, 1, 0], [3, 4, 1]])
np.dot(l,u)

array([[ 1,  2,  4],
       [ 2,  9, 12],
       [ 3, 26, 30]])

б)

Начнем прямой ход метода Гаусса. Для этого из второй вытем первую имноженную на 2, из третьей первую умноженную на 3 и из четвертой первую умноженную на 4

$$\begin{pmatrix}
1 & 1 & 2 & 4\\ 
0 & 3 & 4 & 1\\ 
0 & 15 & 23 & 6\\
0 & 18 & 45 & 17
\end{pmatrix}$$

Далее из третьей вычтем вторую умноженную на 5 и из четвертой вторую умноженную на 6

$$\begin{pmatrix}
1 & 1 & 2 & 4\\ 
0 & 3 & 4 & 1\\ 
0 & 0 & 3 & 1\\
0 & 0 & 21 & 11
\end{pmatrix}$$

Далее из четвертой вычтем третью строку умноженную на 7

$$\begin{pmatrix}
1 & 1 & 2 & 4\\ 
0 & 3 & 4 & 1\\ 
0 & 0 & 3 & 1\\
0 & 0 & 0 & 4
\end{pmatrix}$$


В итоге получим

$$U=\begin{pmatrix}
1 & 1 & 2 & 4\\ 
0 & 3 & 4 & 1\\ 
0 & 0 & 3 & 1\\
0 & 0 & 0 & 4
\end{pmatrix}$$



$$L=\begin{pmatrix}
1 & 0 & 0 & 0\\ 
2 & 1 & 0 & 0\\ 
3 & 5 & 1 & 0\\
4 & 6 & 7 & 0
\end{pmatrix}$$



In [7]:
# проверка
u=np.array([[1, 1, 2, 4], [0, 3, 4, 1], [0, 0, 3, 1], [0, 0, 0, 4]])
l=np.array([[1, 0, 0, 0], [2, 1, 0, 0], [3, 5, 1, 0], [4, 6, 7, 0]])
np.dot(l,u)

array([[ 1,  1,  2,  4],
       [ 2,  5,  8,  9],
       [ 3, 18, 29, 18],
       [ 4, 22, 53, 29]])

__3*.__ Решить систему линейных уравнений методом $LU$-разложения

$$\begin{cases}
2x_{1}+x_{2}+3x_{3}=1 \\
11x_{1}+7x_{2}+5x_{3}=-6 \\
9x_{1}+8x_{2}+4x_{3}=-5
\end{cases}$$

__Решение__

Матрица коэффициентов $A$ будет иметь вид

$$\begin{pmatrix}
2 & 1 & 3 \\ 
11 & 7 & 5 \\ 
9 & 8 & 4
\end{pmatrix}$$

Начнем прямой ход метода Гаусса. Для этого из второй вытем первую имноженную на 5.5, из третьей первую умноженную на 4.5

$$\begin{pmatrix}
2 & 1 & 3 \\ 
0 & 1.5 & -11.5 \\ 
0 & 3.5 & -9.5
\end{pmatrix}$$

Далее из третьей строки вычетаем вторую уиноженную на $\frac{7}{3}$

$$U=\begin{pmatrix}
2 & 1 & 3 \\ 
0 & 1.5 & -11.5 \\ 
0 & 0 & \frac{52}{3}
\end{pmatrix}$$



В итоге получим

$$U=\begin{pmatrix}
2 & 1 & 3 \\ 
0 & 1.5 & -11.5 \\ 
0 & 0 & \frac{52}{3}
\end{pmatrix}$$


$$L=\begin{pmatrix}
1 & 0 & 0 \\ 
5.5 & 1 & 0 \\ 
4.5 & \frac{7}{3} & 1
\end{pmatrix}$$



In [8]:
# проверка
u=np.array([[2, 1, 3], [0, 1.5, -11.5], [0, 0, 52/3]])
l=np.array([[1, 0, 0], [5.5, 1, 0], [4.5, 7/3, 1]])
np.dot(l,u)

array([[ 2.,  1.,  3.],
       [11.,  7.,  5.],
       [ 9.,  8.,  4.]])

Решим теперь систему 

$$Ly=b:$$

$$\begin{cases}
y_{1}=1, \\
5.5y_{1}+y_{2}=-6, \\
4.5y_{1}+\frac{7}{3}y_{2}+y_{3}=-5
\end{cases}$$

$$y_{1}=1,$$
$$y_{2}=-11.5,$$
$$y_{3}=\frac{52}{3}$$


И затем систему

$$Ux=y:$$

$$\begin{cases}
2x_{1}+1x_{2}+3x_{3}=1, \\
1.5x_{2}-11.5x_{3}=-11.5, \\
\frac{52}{3}x_{3}=\frac{52}{3}.
\end{cases}$$

$$x_{3}=1$$

$$x_{2}=0$$

$$x_{1}=-1$$



__4*.__ Решить систему линейных уравнений методом Холецкого

$$\begin{cases}
81x_{1}-45x_{2}+45x_{3}=531 \\
-45x_{1}+50x_{2}-15x_{3}=-460 \\
45x_{1}-15x_{2}+38x_{3}=193
\end{cases}$$

__Решение:__

Произведем разложение на $LL^{T}$:

$$l_{11}=\sqrt{a_{11}}=\sqrt{81}=9,$$
$$l_{21}=\frac{a_{21}}{l_{11}}=\frac{-45}{9}=-5,$$
$$l_{31}=\frac{a_{31}}{l_{11}}=\frac{45}{9}=5,$$

$$l_{22}=\sqrt{a_{22}-l_{21}^{2}}=\sqrt{50 - 25}=5,$$
$$l_{32}=\frac{1}{l_{22}}\left ( a_{32}-l_{21}l_{31} \right)=\frac{1}{5} (-15-(-5)\cdot 5)=\frac{1}{5}\cdot 10=2$$

$$l_{33}=\sqrt{a_{33}-l_{31}^{2}-l_{32}^{2}}=\sqrt{38-25-4}=3.$$

Получили матрицу 

$$L = \begin{pmatrix}
9 & 0 & 0 \\ 
-5 & 5 & 0 \\ 
5 & 2 & 3
\end{pmatrix}, 
\; \; 
L^{T} = \begin{pmatrix}
9 & -5 & 5 \\ 
0 & 5 & 2 \\ 
0 & 0 & 3
\end{pmatrix}.$$


Решим систему $Ly=b:$

$$\begin{cases}
9y_{1}=531, \\
-5y_{1}+5y_{2}=-460, \\
5y_{1}+2y_{2}+3y_{3}=193.
\end{cases}$$

$$y_{1} = 59,$$

$$y_{2}=-33,$$

$$y_{3}=-12.$$

И решим систему $L^{T}x=y:$

$$\begin{cases}
9x_{1}-5x_{2}+5x_{3}=59, \\
5x_{2}+2x_{3}=-33, \\
3x_{3}=-12.
\end{cases}$$

$$x_{3}=-4$$

$$x_{2}=-5$$

$$x_{1}=6$$



__5*.__ Написать на Python программу с реализацией одного из изученных алгоритмов решения СЛАУ.

In [138]:
def decompose_to_LU(a):
    #Разложение матрицы коэффициентов на матрицы L и U.
    #Треугольные матрицы L и U будут представлены в одной матрице размера nxn.
    
    lu_matrix = np.matrix(np.zeros([a.shape[0], a.shape[1]]))
    n = a.shape[0]
    for k in range(n):
        for j in range(k, n):
            lu_matrix[k, j] = a[k, j] - lu_matrix[k, :k] * lu_matrix[:k, j]
        for i in range(k + 1, n):
            lu_matrix[i, k] = (a[i, k] - lu_matrix[i, : k] * lu_matrix[: k, k]) / lu_matrix[k, k]

    return lu_matrix

In [139]:
def get_L(m):
    # получаем L матрицу
    L = m.copy()
    for i in range(L.shape[0]):
            L[i, i] = 1
            L[i, i+1 :] = 0
    return np.matrix(L)


def get_U(m):
    # получаем U матрицу
    U = m.copy()
    for i in range(1, U.shape[0]):
        U[i, :i] = 0
    return U

In [140]:
def solve_LU(lu_matrix,b):
    # Решаем систему уровнение.
    
    y = np.matrix(np.zeros([lu_matrix.shape[0], 1]))
    for i in range(y.shape[0]):
        y[i, 0] = b[i, 0] - lu_matrix[i, :i] * y[:i]

    x = np.matrix(np.zeros([lu_matrix.shape[0], 1]))
    for i in range(1, x.shape[0] + 1):
        x[-i, 0] = (y[-i] - lu_matrix[-i, -i:] * x[-i:, 0] )/ lu_matrix[-i, -i]

    return x

In [141]:
## Проверка
a= np.array([[2, 1, 1], [4, -6, 0], [-2, 7, 2]])
b= np.array([[5], [-2], [9]])
decompose_to_LU(a)

matrix([[ 2.,  1.,  1.],
        [ 2., -8., -2.],
        [-1., -1.,  1.]])

In [142]:
LU = decompose_to_LU(a)
L = get_L(LU)
U = get_U(LU)

In [143]:
L

matrix([[ 1.,  0.,  0.],
        [ 2.,  1.,  0.],
        [-1., -1.,  1.]])

In [144]:
U

matrix([[ 2.,  1.,  1.],
        [ 0., -8., -2.],
        [ 0.,  0.,  1.]])

In [145]:
np.dot(L, U)

matrix([[ 2.,  1.,  1.],
        [ 4., -6.,  0.],
        [-2.,  7.,  2.]])

In [146]:
solve_LU(LU, b)

matrix([[1.],
        [1.],
        [2.]])